/**
 * Generates the preflop hand ranking used by the AI (src/core/preflopRanking.ts).
 * Score blends equity vs one random hand and vs three random hands, so suited
 * connectors rank sensibly for multiway pots. Run: npx tsx scripts/gen-preflop-ranking.ts
 */
import { writeFileSync } from 'node:fs';
import { handClass, handClassLabel, handClassCombos, makeCard } from '../src/core/cards';
import { evaluate } from '../src/core/evaluator';
import { Rng } from '../src/core/rng';

const rng = new Rng('preflop-ranking-v1');
const ITERS = 50000;

function representative(cls: number): [number, number] {
  for (let a = 0; a < 52; a++) for (let b = a + 1; b < 52; b++) if (handClass(a, b) === cls) return [a, b];
  throw new Error('no combo');
}

function equity(hero: [number, number], opponents: number): number {
  let won = 0;
  const deck: number[] = [];
  for (let c = 0; c < 52; c++) if (c !== hero[0] && c !== hero[1]) deck.push(c);
  const cards = new Int32Array(7);
  for (let it = 0; it < ITERS; it++) {
    // Partial Fisher-Yates for 5 board + 2*opponents cards.
    const need = 5 + 2 * opponents;
    for (let i = 0; i < need; i++) {
      const j = i + rng.int(deck.length - i);
      const t = deck[i]; deck[i] = deck[j]; deck[j] = t;
    }
    cards[0] = hero[0]; cards[1] = hero[1];
    for (let i = 0; i < 5; i++) cards[2 + i] = deck[i];
    const hs = evaluate(cards, 7);
    let ties = 1; let heroBest = true;
    for (let o = 0; o < opponents; o++) {
      cards[0] = deck[5 + 2 * o]; cards[1] = deck[6 + 2 * o];
      const os = evaluate(cards, 7);
      if (os > hs) { heroBest = false; break; }
      if (os === hs) ties++;
    }
    if (heroBest) won += 1 / ties;
  }
  return won / ITERS;
}

const rows: { cls: number; label: string; score: number; eq1: number; eq3: number }[] = [];
for (let cls = 0; cls < 169; cls++) {
  const hero = representative(cls);
  const eq1 = equity(hero, 1);
  const eq3 = equity(hero, 3);
  rows.push({ cls, label: handClassLabel(cls), eq1, eq3, score: (eq1 / 0.5) * 0.55 + (eq3 / 0.25) * 0.45 });
}
rows.sort((a, b) => b.score - a.score);

const order = rows.map((r) => r.cls);
const eq1 = new Array(169).fill(0);
for (const r of rows) eq1[r.cls] = Math.round(r.eq1 * 1000) / 1000;

let cum = 0;
const summary = rows.map((r) => { cum += handClassCombos(r.cls); return `${r.label}:${(cum / 1326 * 100).toFixed(1)}`; });

const out = `// Generated by scripts/gen-preflop-ranking.ts. Do not edit by hand.
// Strongest first. Blend of equity vs 1 and vs 3 random hands.
// ${summary.slice(0, 20).join(' ')}

/** Hand classes (see handClass in cards.ts) ordered strongest to weakest. */
export const PREFLOP_ORDER: readonly number[] = ${JSON.stringify(order)};

/** Heads-up equity of each hand class vs a random hand. */
export const PREFLOP_EQUITY_HU: readonly number[] = ${JSON.stringify(eq1)};
`;
writeFileSync(new URL('../src/core/preflopRanking.ts', import.meta.url), out);
console.log(summary.slice(0, 40).join('  '));
console.log('...', summary.slice(150).join('  '));
