/**
 * Golden test vectors for the C++ port (ShortStackCore).
 *
 * Runs the TypeScript engine on seeded inputs and records exact results:
 * doubles as IEEE-754 bit patterns, hands and tournaments as FNV-1a hashes of
 * a canonical event log. The C++ test runner replays every record and must
 * match bit for bit.
 *
 * Run: npx tsx scripts/gen-golden.ts
 * Output: unreal/Plugins/ShortStackCore/Tests/golden_vectors.txt
 */
import { mkdirSync, writeFileSync } from 'node:fs';
import { dirname } from 'node:path';
import { fullDeck, handClass } from '../src/core/cards';
import { CLASS_PERCENTILE, equityKnownHands, equityVsRanges, RangeBand } from '../src/core/equity';
import { describe, evaluate } from '../src/core/evaluator';
import { Hand, HandEvent, PlayerAction } from '../src/core/hand';
import { uniqueNames } from '../src/core/names';
import { Rng } from '../src/core/rng';
import { icm, payoutTable } from '../src/core/structure';
import { Tournament, TournamentSpec } from '../src/core/tournament';
import { decide } from '../src/core/ai/bot';
import { analyzeDecision, gradeDecision } from '../src/core/ai/grading';
import { Archetype, makeProfile, Profile, sprintProfile } from '../src/core/ai/profiles';
import { makeView } from '../src/core/ai/view';
import { detPow } from '../src/core/detmath';

const OUT = new URL('../../unreal/Plugins/ShortStackCore/Tests/golden_vectors.txt', import.meta.url).pathname;
const lines: string[] = ['# ShortStackCore golden vectors v1. Generated by web/scripts/gen-golden.ts. Do not edit.'];
const emit = (...parts: (string | number)[]) => lines.push(parts.join(' '));

// ------------------------------------------------------------------ encoding helpers

const dv = new DataView(new ArrayBuffer(8));
export function hx(x: number): string {
  dv.setFloat64(0, x);
  return dv.getBigUint64(0).toString(16).padStart(16, '0');
}
export function fnv(s: string): number {
  let h = 2166136261;
  for (let i = 0; i < s.length; i++) {
    h ^= s.charCodeAt(i);
    h = Math.imul(h, 16777619) >>> 0;
  }
  return h;
}
const word = (s: string) => s.replace(/ /g, '_');
const STREET: Record<string, string> = { preflop: 'p', flop: 'f', turn: 't', river: 'r', showdown: 's' };
const ATYPE: Record<string, string> = { fold: 'f', check: 'k', call: 'c', bet: 'b', raise: 'r' };

/** Canonical event log; C++ builds the identical string (see golden.cpp). */
export function eventLog(events: HandEvent[]): string {
  let s = '';
  for (const e of events) {
    switch (e.t) {
      case 'ante': s += `A${e.seat},${e.amount};`; break;
      case 'blind': s += `B${e.kind === 'sb' ? 's' : 'b'}${e.seat},${e.amount};`; break;
      case 'deal': s += `D${e.order.join(',')};`; break;
      case 'action': s += `X${STREET[e.street]}${e.seat}${ATYPE[e.type]},${e.added},${e.to},${e.allIn ? 1 : 0},${e.potBefore},${e.facing};`; break;
      case 'street': s += `S${STREET[e.street]}${e.cards.join(',')};`; break;
      case 'return': s += `R${e.seat},${e.amount};`; break;
      case 'reveal': s += `V${e.seats.join(',')};`; break;
      case 'showdown': s += `W${e.hands.map((h) => `${h.seat}:${h.hole.join(',')}:${h.score}`).join('|')};`; break;
      case 'award': s += `P${e.index}/${e.potCount}:${e.pot.amount}:${e.pot.eligible.join(',')}:${e.pot.winners.join(',')}:${e.pot.shares.join(',')};`; break;
      case 'end': s += 'E;'; break;
    }
  }
  return s;
}
const actionToken = (a: PlayerAction) => (a.type === 'raise' ? `r:${a.to}` : a.type[0] === 'c' ? (a.type === 'call' ? 'c' : 'k') : 'f');

// ------------------------------------------------------------------ rng

for (const seed of ['1', 'golden', 'night-owl:1727650000', '12345', 'fold:equity']) {
  const r = new Rng(seed);
  const u: number[] = [];
  for (let i = 0; i < 24; i++) u.push(r.nextUint32());
  emit('rng', seed, u.length, ...u);
  const ri = new Rng(seed);
  const ints: number[] = [];
  for (let i = 0; i < 24; i++) ints.push(ri.int(7 + i * 13));
  emit('rngint', seed, ints.length, ...ints);
  const rf = new Rng(seed);
  const fl: string[] = [];
  for (let i = 0; i < 12; i++) fl.push(hx(rf.next()));
  for (let i = 0; i < 6; i++) fl.push(hx(rf.gauss(1.5, 0.3)));
  emit('rngf', seed, fl.length, ...fl);
  const rs = new Rng(seed);
  emit('shuffle', seed, ...rs.shuffle(fullDeck()));
  const f = new Rng(seed).fork('names');
  emit('fork', seed, 'names', f.nextUint32(), f.nextUint32(), f.nextUint32());
}
emit('detpow', hx(detPow(0.37, 2.2)), hx(detPow(7, 0.95)), hx(detPow(113, 0.85)), hx(detPow(0.61, 1)), hx(detPow(0.5, 0)));

// ------------------------------------------------------------------ evaluator

{
  const r = new Rng('eval');
  const deck = fullDeck();
  for (let t = 0; t < 3000; t++) {
    r.shuffle(deck);
    const n = t % 3 === 0 ? 5 : t % 3 === 1 ? 6 : 7;
    const cards = deck.slice(0, n);
    emit('eval', n, ...cards, evaluate(cards));
  }
  const special = ['AsKsQsJsTs', '5s4s3s2sAs', '9h9d9c9s2d', 'KhKdKc2s2d', '8h8d8c3s3d3cAh', 'KhKd9c9s4d4cAh', '5c4d3h2sAd'];
  for (const sp of special) {
    const cards: number[] = [];
    for (let i = 0; i < sp.length; i += 2) cards.push('23456789TJQKA'.indexOf(sp[i]) * 4 + 'cdhs'.indexOf(sp[i + 1]));
    const sc = evaluate(cards);
    emit('desc', sc, word(describe(sc)));
  }
  for (let t = 0; t < 60; t++) {
    r.shuffle(deck);
    const sc = evaluate(deck.slice(0, 7));
    emit('desc', sc, word(describe(sc)));
  }
}

// ------------------------------------------------------------------ equity

emit('pct', ...Array.from(CLASS_PERCENTILE, (v) => hx(v)));
{
  const r = new Rng('equity');
  const deck = fullDeck();
  for (let t = 0; t < 40; t++) {
    r.shuffle(deck);
    const players = 2 + (t % 3);
    const boardN = t % 2 === 0 ? 3 : 4;
    const hands = Array.from({ length: players }, (_, i) => deck.slice(i * 2, i * 2 + 2));
    const board = deck.slice(players * 2, players * 2 + boardN);
    const eq = equityKnownHands(hands, board, new Rng('unused'));
    emit('eqk', players, ...hands.flat(), boardN, ...board, ...eq.map(hx));
  }
  for (let t = 0; t < 10; t++) {
    r.shuffle(deck);
    const hands = [deck.slice(0, 2), deck.slice(2, 4)];
    const seed = `eqmc${t}`;
    const eq = equityKnownHands(hands, [], new Rng(seed), 3000);
    emit('eqkmc', seed, 3000, 2, ...hands.flat(), ...eq.map(hx));
  }
  for (let t = 0; t < 30; t++) {
    r.shuffle(deck);
    const boardN = [0, 3, 4, 5][t % 4];
    const hero = deck.slice(0, 2);
    const board = deck.slice(2, 2 + boardN);
    const ranges: RangeBand[] = [];
    const nr = 1 + (t % 3);
    for (let i = 0; i < nr; i++) ranges.push({ min: [0, 0.02, 0.05][i % 3], max: [1, 0.35, 0.12][(t + i) % 3] });
    const seed = `eqr${t}`;
    const e = equityVsRanges(hero, board, ranges, 400, new Rng(seed));
    emit('eqr', seed, 400, ...hero, boardN, ...board, nr, ...ranges.flatMap((b) => [hx(b.min), hx(b.max)]), hx(e));
  }
}

// ------------------------------------------------------------------ hands (random legal actions)

{
  const r = new Rng('hands');
  for (let t = 0; t < 400; t++) {
    const n = 2 + r.int(8);
    const stacks = Array.from({ length: n }, () => 1 + r.int(20000));
    const button = r.int(n);
    const ante = r.chance(0.5) ? 100 : 0;
    const seed = `hand${t}`;
    const h = new Hand({ players: stacks.map((stack, seat) => ({ seat, id: `p${seat}`, stack })), buttonSeat: button, smallBlind: 50, bigBlind: 100, ante, rng: new Rng(seed) });
    const actions: string[] = [];
    while (!h.complete) {
      const legal = h.legalActions();
      const roll = r.next();
      let a: PlayerAction;
      if (roll < 0.15) a = { type: 'fold' };
      else if (roll < 0.6) a = legal.canCheck ? { type: 'check' } : { type: 'call' };
      else if (legal.canRaise) a = { type: 'raise', to: legal.minRaiseTo + r.int(Math.max(1, legal.maxRaiseTo - legal.minRaiseTo + 1)) };
      else a = { type: 'call' };
      actions.push(actionToken(a));
      h.act(a);
    }
    emit('hand', seed, n, button, 50, 100, ante, ...stacks, actions.length, ...actions, '|', ...h.seats.map((s) => s.stack), fnv(eventLog(h.events)));
  }
}

// ------------------------------------------------------------------ profiles

const ARCHS: Archetype[] = ['fish', 'station', 'nit', 'tag', 'lag', 'maniac', 'reg', 'crusher'];
const profileFields = (p: Profile) => [p.openWidth, p.limpRate, p.threeBet, p.callWidth, p.aggression, p.bluff, p.stickiness, p.cbet, p.sizing, p.tiltProne, p.pushFold, p.icmAware, p.thinkBase, p.thinkVar];
{
  const r = new Rng('profiles');
  for (let t = 0; t < 24; t++) {
    const a = ARCHS[t % ARCHS.length];
    const p = makeProfile(a, r);
    emit('profile', 'profiles', t, a, p.timing, ...profileFields(p).map(hx));
  }
}

// ------------------------------------------------------------------ bot hands and grading

{
  const r = new Rng('bothands');
  for (let t = 0; t < 160; t++) {
    const fast = t % 2 === 1;
    const n = 2 + r.int(8);
    const stacks = Array.from({ length: n }, () => 200 + r.int(30000));
    const archs = Array.from({ length: n }, () => ARCHS[r.int(ARCHS.length)]);
    const tilts = Array.from({ length: n }, () => (r.chance(0.3) ? r.next() : 0));
    const pressures = Array.from({ length: n }, () => (r.chance(0.3) ? r.next() : 0));
    const button = r.int(n);
    const ante = t % 3 === 0 ? 0 : 100;
    const seed = `bot${t}`;
    const rng = new Rng(seed);
    const prng = new Rng(`prof${t}`);
    const profiles = archs.map((a) => makeProfile(a, prng));
    const h = new Hand({ players: stacks.map((stack, seat) => ({ seat, id: `p${seat}`, stack })), buttonSeat: button, smallBlind: 50, bigBlind: 100, ante, rng });
    const decisions: string[] = [];
    const grades: string[] = [];
    let k = 0;
    while (!h.complete) {
      const idx = h.toAct!;
      const seat = h.seats[idx].seat;
      const view = makeView(h, idx);
      // Grade every decision seat 0 makes (non-fast hands only, to keep the file small).
      let analysis = null;
      if (!fast && seat === 0) analysis = analyzeDecision(makeView(h, idx), new Rng(`g${t}:${k}`), 300);
      const d = decide(view, { profile: profiles[seat], tilt: tilts[seat], icmPressure: pressures[seat], fast, rng });
      decisions.push(`${actionToken(d.action)}/${hx(d.thinkMs)}/${hx(d.equity)}`);
      if (analysis) {
        const g = gradeDecision(analysis, d.action);
        grades.push(
          [k, hx(analysis.equity), hx(analysis.potOdds), analysis.options.length, ...analysis.options.flatMap((o) => [word(o.label), actionToken(o.action), hx(o.ev)]), g.grade, word(g.chosen.label), hx(g.chosen.ev), word(g.best.label), hx(g.lossBB), word(g.note)].join(' '),
        );
      }
      h.act(d.action);
      k++;
    }
    emit('bothand', seed, fast ? 1 : 0, n, button, 50, 100, ante, ...stacks, ...archs, ...tilts.map(hx), ...pressures.map(hx), `prof${t}`, '|', decisions.length, ...decisions, '|', ...h.seats.map((s) => s.stack), fnv(eventLog(h.events)), rng.nextUint32());
    for (const g of grades) emit('grade', seed, g);
  }
}

// ------------------------------------------------------------------ structure

for (const [pool, entrants, minCash] of [[100000, 1000, 140], [4140, 180, 32], [5000, 1000, 20], [900, 9, 140], [3000, 30, 140], [50000, 45, 1400], [100, 3, 0], [123457, 777, 150]]) {
  const p = payoutTable(pool, entrants, minCash);
  emit('payout', pool, entrants, minCash, p.length, ...p);
}
{
  const r = new Rng('icm');
  for (let t = 0; t < 14; t++) {
    const n = 2 + (t % 8);
    const stacks = Array.from({ length: n }, () => 1000 + r.int(900000));
    const m = 1 + r.int(n);
    const prizes = Array.from({ length: m }, (_, i) => Math.round(100000 / (i + 1)));
    emit('icm', n, ...stacks, m, ...prizes, ...icm(stacks, prizes).map(hx));
  }
}

// ------------------------------------------------------------------ names

for (const seed of ['names1', 'names2']) {
  const reserved = ['Hero', 'gh0stfold'];
  const names = uniqueNames(300, new Rng(seed), reserved);
  emit('names', seed, names.length, reserved.length, ...reserved, ...names);
}

// ------------------------------------------------------------------ tournaments

function runTourney(spec: TournamentSpec, seed: string, maxTicks: number) {
  const t = new Tournament(spec, 'Hero', seed, [{ name: 'gh0stfold', archetype: 'crusher' }]);
  const specTokens = [spec.id, spec.buyInCents, spec.feeCents, spec.guaranteeCents, spec.entrants, spec.startingStack, spec.levelMinutes, spec.secondsPerHand, spec.population, spec.speed, spec.startClock];
  emit('tourney', seed, maxTicks, ...specTokens);
  // Checkpoint the full state every round so a divergence is pinpointed.
  while (!t.finished && t.tick < maxTicks) {
    if (t.tick === 12) t.moveToTable('npc:gh0stfold', t.hero.tableId);
    const ev = t.simulateTick(sprintProfile());
    let s = '';
    for (const p of t.players.values()) s += `${p.id}:${p.stack}:${p.tableId}:${p.seat}:${p.busted ? p.place : 0};`;
    for (const e of ev) s += `${e.t}:${'place' in e ? e.place : ''}:${'id' in e ? e.id : ''}:${'to' in e ? e.to : ''}:${'tableId' in e ? e.tableId : ''};`;
    emit('tick', seed, t.tick, t.remaining, t.levelIndex, fnv(s));
  }
  const res = [...t.players.values()].map((p) => `${p.id}=${p.busted || p.place === 1 ? p.place : 0}/${p.prizeCents}`);
  emit('tresult', seed, t.tick, t.remaining, t.finished ? 1 : 0, t.prizePoolCents, t.payouts.length, res.length, ...res);
}
const base = { startingStack: 10000, secondsPerHand: 42, tableSize: 9 } as const;
runTourney({ ...base, id: 'hyper-sprint', name: '$0.25 Hyper Sprint', buyInCents: 25, feeCents: 2, guaranteeCents: 0, entrants: 180, levelMinutes: 3, population: 'micro', speed: 'Hyper', startClock: 131 }, 'golden-hyper', 100000);
runTourney({ ...base, id: 'night-owl', name: '$1.10 Night Owl Turbo', buyInCents: 110, feeCents: 10, guaranteeCents: 100000, entrants: 1000, levelMinutes: 5, population: 'micro', speed: 'Turbo', startClock: 131 }, 'golden-owl', 40);
runTourney({ ...base, id: 'freeroll', name: 'Midnight Freeroll', buyInCents: 0, feeCents: 0, guaranteeCents: 5000, entrants: 45, levelMinutes: 4, population: 'freeroll', speed: 'Turbo', startClock: 131 }, 'golden-free', 100000);

mkdirSync(dirname(OUT), { recursive: true });
writeFileSync(OUT, lines.join('\n') + '\n');
console.log(`${lines.length} records, ${(lines.join('\n').length / 1024).toFixed(0)} KB -> ${OUT}`);
void handClass;
