/** Writes the preflop tables into the C++ port so both builds share one source of truth. */
import { writeFileSync } from 'node:fs';
import { PREFLOP_EQUITY_HU, PREFLOP_ORDER } from '../src/core/preflopRanking';
const out = new URL('../../unreal/Plugins/ShortStackCore/Source/ShortStackCore/Private/ShortStack/PreflopRanking.cpp', import.meta.url).pathname;
const src = `// Generated by web/scripts/gen-cpp-tables.ts from web/src/core/preflopRanking.ts. Do not edit.
#include "ShortStack/Equity.h"

namespace ss
{
const int PreflopOrder[169] = {${PREFLOP_ORDER.join(', ')}};

const double PreflopEquityHU[169] = {${PREFLOP_EQUITY_HU.map((v) => String(v)).join(', ')}};
} // namespace ss
`;
writeFileSync(out, src);
console.log('wrote', out);
